---
title: Defund12.org
timezone: UTC
collections:
  emails:
    title: Emails
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: emails
  values:
    layout: email
    permalink: "/desired-path"
    name: Title of letter (e.g. Letter to City Council)
    city: City
    state: State intials
    recipients:
    -
    subject: Email subject (mention defunding police dept.)
    body: Email message (remember to include placeholders for name)
permalink: pretty
subtitle: Email government officials and council members to reallocate egregious police
  budgets towards education, social services, and dismantling racial inequality via
  this crowd-sourced tool.
meta: Email government officials and council members to reallocate police budgets
  towards education, social services, and dismantling racial inequality.
footer_text: |-
  Want to add your city? [Open a request.](https://github.com/teddywilson/defund12.org/issues)

  Have the emails of your city government officials and a drafted template ready.
contact_email_footer: |-
  [contact@defund12.org](mailto:contact@defund12.org)
default_subject_line: "[*** INSERT UNIQUE SUBJECT LINE***]"
auto_open_message: This page automatically opens a drafted email for you.
bad_mailto_message: Email link not working correctly? You can copy and paste the recipients,
  subject and message individually below.
url: https://defund12.org
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
